import { GroupType } from "./schemas";

export const INITIAL_GROUPS: GroupType[] = [
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678901",
    title: "Hawker Crawlers SG (Maxwell & Old Airport Rd)",
    interest_tag: "food",
    description: "Weekly culinary meetups exploring legendary hawker stalls, sharing tze char feasts, and learning local kopi ordering customs together.",
    external_link: "https://t.me/sg_hawker_crawlers",
    next_event_at: "2026-08-22T11:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678902",
    title: "MacRitchie & Southern Ridges Trail Trekkers",
    interest_tag: "outdoors",
    description: "Early Saturday morning nature hikes across TreeTop Walk, Southern Ridges canopy boardwalks, and Bukit Timah rainforest trails.",
    external_link: "https://chat.whatsapp.com/invite/SgTrailTrekkers2026",
    next_event_at: "2026-08-23T00:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678903",
    title: "Gillman Barracks & Art After Dark Collective",
    interest_tag: "arts",
    description: "Monthly gallery hops, contemporary exhibition previews at SAM Tanjong Pagar Distripark, and casual art discussions over craft drinks.",
    external_link: "https://t.me/sg_arts_collective",
    next_event_at: "2026-08-28T10:30:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678904",
    title: "East Coast Park Sunset Beach Volleyball & Run",
    interest_tag: "sports",
    description: "All-levels casual volleyball games and coastal 5k sunset jogs followed by fresh coconut water and satay at Parkland Green.",
    external_link: "https://chat.whatsapp.com/invite/EcpVolleyRunSg",
    next_event_at: "2026-08-24T09:30:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678905",
    title: "SG Tech Founders & Expat Professional Circle",
    interest_tag: "professional",
    description: "Bi-weekly breakfast mixers at Tanjong Pagar for engineers, designers, founders, and students new to Singapore's tech ecosystem.",
    external_link: "https://t.me/sg_expat_founders",
    next_event_at: "2026-08-27T00:30:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678906",
    title: "Singlish & Conversational Mandarin Coffee Exchange",
    interest_tag: "language",
    description: "Friendly peer language exchanges over iced kopi at Bugis and Chinatown. Practice conversational Mandarin, Singlish nuances, and Hokkien loanwords.",
    external_link: "https://chat.whatsapp.com/invite/SgLanguageExchange",
    next_event_at: "2026-08-25T11:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678907",
    title: "Sentosa Sunset Ocean Kayaking & Eco-Paddlers",
    interest_tag: "sports",
    description: "Weekend sea kayaking and paddle sessions off Palawan & Siloso beach. Equipment rental coordination and periodic coastal cleanups.",
    external_link: "https://t.me/sg_coastal_paddlers",
    next_event_at: "2026-08-30T01:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678908",
    title: "Jalan Besar Specialty Coffee & Urban Sketchers",
    interest_tag: "arts",
    description: "Quiet Saturday morning sketch meetups capturing heritage shophouses, ornate ceramic tiles, and enjoying pour-overs around Lavender & Jalan Besar.",
    external_link: "https://chat.whatsapp.com/invite/JalanBesarSketchers",
    next_event_at: "2026-08-29T02:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678909",
    title: "Marina Bay Sunrise Dragon Boating & Fitness",
    interest_tag: "sports",
    description: "Novice-friendly dragon boat training sessions on Kallang Basin with skyline views of Marina Bay Sands. Teamwork and full-body cardio.",
    external_link: "https://t.me/sg_dragonboat_beginners",
    next_event_at: "2026-09-05T00:00:00.000Z",
  },
  {
    id: "a1b2c3d4-e5f6-4a7b-8c9d-012345678910",
    title: "Clarke Quay Tabletop & Board Game Socials",
    interest_tag: "other",
    description: "Relaxed mid-week strategy and party board game evenings at casual cafes along the Singapore River. Great for making new friends.",
    external_link: "https://chat.whatsapp.com/invite/ClarkeQuayBoardgames",
    next_event_at: "2026-08-26T11:30:00.000Z",
  }
];
